### ISSUE TITLE
error when building/running in lollipop

### ISSUE THREAD

**Issue by brendanclement** [theksmith/CarBusInterface#5]
Just downloaded your project and trying to build/run it but not having luck.
I’m using Nexus 7 running latest version of android.
appears that the apks in the “Recent Builds” don’t run — so I ran the source code in android studio and got the following error:

Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference

05-25 21:08:27.448  14541-14541/com.theksmith.android.car_bus_interface I/art﹕ Not late-enabling -Xcheck:jni (already on)
05-25 21:08:27.469  14541-14541/com.theksmith.android.car_bus_interface D/CBIActivityMain﹕ appCheckForFirstRun()
05-25 21:08:27.481  14541-14541/com.theksmith.android.car_bus_interface D/CBIActivityMain﹕ onCreate() : action= android.intent.action.MAIN
05-25 21:08:27.481  14541-14541/com.theksmith.android.car_bus_interface D/CBIActivityMain﹕ serviceMainStart()
05-25 21:08:27.499  14541-14541/com.theksmith.android.car_bus_interface D/CBIServiceMain﹕ CBIServiceMain()
05-25 21:08:27.499  14541-14541/com.theksmith.android.car_bus_interface D/AndroidRuntime﹕ Shutting down VM
05-25 21:08:27.500  14541-14541/com.theksmith.android.car_bus_interface E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.theksmith.android.car_bus_interface, PID: 14541
    java.lang.RuntimeException: Unable to instantiate service com.theksmith.android.car_bus_interface.CBIServiceMain: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2749)
            at android.app.ActivityThread.access$1800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
            at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:149)
            at android.app.Notification$Builder.<init>(Notification.java:2041)
            at com.theksmith.android.car_bus_interface.CBIServiceMain.<init>(CBIServiceMain.java:109)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1606)
           at android.app.ActivityThread.handleCreateService(ActivityThread.java:2746)
            at android.app.ActivityThread.access$1800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

![image](https://cloud.githubusercontent.com/assets/1138958/7853521/55a9efe8-04c4-11e5-9395-675a85343773.png)

**Comment by theksmith** [comment]
@brendanclement - merged your changes, thanks! did that fix it completely or was this just the first of several steps to getting it fixed on Lollipop?

**Comment by brendanclement** [comment]
No that fixed it completely

I'm running it now

**Comment by theksmith** [comment]
sweet!
